version: "3.11"
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    image: yourusername/image-name:latest
    container_name: container-name
    command: python3 manage.py runserver 0.0.0.0:8000
    env_file:
      - config/.env
